print ('==============DESAFIO #2==============')
nome = input ('Qual é o seu nome?')
dia = input ('Qual o dia de seu nascimento?')
mes = input ('Qual o mes de seu nascimento?')
ano = input ('Qual o ano de seu nascimento?')
print ('Olá', nome,'! Prazer em te conhecer!')
print ('Você nasceu em:', dia,'/',mes,'/',ano)
